Repository findyourexit/open-arbitrage, pull requests merged in 2022-02, with the labels that each got.

#1 Enhancement: Buy/Sell Hints
  main.py
Labels: enhancement

#4 Bugfix: Change City Menu Formatting
  main.py
Labels: bug

#6 Enhancement: Improved Market Fluctuation/Reroll
  README.md
  main.py
  marketplace.py
  player.py
Labels: enhancement

#8 Updated gitignore with the official Python gitignore
  .gitignore
Labels: documentation

#7 Created requirements file which allows the simple installation of all dependencies via pip command
  requirements.txt
Labels: documentation
